### ISSUE TITLE
employer compile error

### ISSUE THREAD

**Issue by smthpickboy** [mycodesmells/golang-examples#2]
https://github.com/mycodesmells/golang-examples/blob/89ce2beca34271bea239b9ff5f04a56781320ad1/k8s/grpc-pooling/employer/main.go#L82

https://github.com/mycodesmells/golang-examples/blob/89ce2beca34271bea239b9ff5f04a56781320ad1/k8s/grpc-pooling/employer/main.go#L85

These 2 lines won't compile.

**Comment by slomek** [comment]
Thanks @smthpickboy! Fixed in https://github.com/mycodesmells/golang-examples/commit/3e486769b05a63335c6b8681c6db9ab752c91481.
