### ISSUE TITLE
Please add Topics to repo

### ISSUE THREAD

**Issue by markbates** [mycodesmells/golang-examples#4]
Hi, I working on a project that will be announced soon to help with the discovery of these sorts of tools. Would you please mind adding some "Topics" to this repo? Thanks.

On GitHub you can use the "Topics" feature of your repository to tag your projects with `gobuffalo` and other category tags.

There are a few more tags that you can use that will help the Buffalo Toolkit better categorize your project. You can add as many of this tags to your project as is suitable. Please try to refrain from using more than just a few tags.

* `plugin` - Plugins
* `generator` - Generators
* `middleware` - Middleware
* `pop` - Pop/Soda
* `templating` - Templating
* `grifts` - Grift Tasks
* `deployment` - Deployment
* `testing` - Testing
* `example` - Example Apps
* `worker` - Workers/Adapters
* `webpack` - Webpack/Front-End

**Comment by slomek** [comment]
I've added a few tags, including `gobuffalo` 😉
